### ISSUE TITLE
Customizable message

### ISSUE THREAD

**Issue by arcanis** [jackrzhang/react-custom-proptypes#1]
It would be nice if the error messages could be customized with infos from the prop itself. For example:

```
Invalid prop, expected number, got a string
```

Instead of just:

```
Invalid prop, expected number
```

**Comment by Darksider3** [comment]
The author didn't commit or comment on his repositorys since october 2016. I think he discontinued most of the work here, sadly. 😢

**Comment by jackrzhang** [comment]
Thanks for the suggestion! See #3.
